[[plugins]]
  repo = 'petobens/poet-v'
  on_ft = ['python']

[[plugins]]
  repo = 'python-lsp/python-lsp-black'
  on_ft = ['python']

[[plugins]]
  repo = 'chantera/python-lsp-isort'
  on_ft = ['python']

[[plugins]]
  repo = 'psf/black'
  on_ft = ['python']
