[[plugins]]
  repo = 'Shougo/dein.vim'

[[plugins]]
  repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
  repo = 'gabrielelana/vim-markdown'

[[plugins]]
  repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
  repo = 'scrooloose/nerdtree'

[[plugins]]
  repo = 'Shougo/neosnippet'

[[plugins]]
  repo = 'Shougo/neosnippet-snippets'

[[plugins]]
  repo = 'tomasr/molokai'

[[plugins]]
  repo = 'vim-scripts/EnhCommentify.vim'

[[plugins]]
  repo = 'Shougo/ddc.vim'

[[plugins]]
  repo = 'vim-denops/denops.vim'

[[plugins]]
  repo = 'Shougo/pum.vim'

[[plugins]]
  repo = 'Shougo/ddc-around'

[[plugins]]
  repo = 'LumaKernel/ddc-file'

[[plugins]]
  repo = 'shun/ddc-vim-lsp'

[[plugins]]
  repo = 'Shougo/ddc-matcher_head'

[[plugins]]
  repo = 'Shougo/ddc-ui-native'

[[plugins]]
  repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
  repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
  repo = 'rhysd/vim-healthcheck'

[[plugins]]
  repo = 'mattn/vim-lsp-settings'

[[plugins]]
  repo = 'prabirshrestha/vim-lsp'

[[plugins]]
  repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'halkn/lightline-lsp'

[[plugins]]
repo = 'itchyny/lightline.vim'
